global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'noxid_metrics'
    metrics_path: /metrics_noxid
    static_configs:
      - targets: ['ecommerce:8000']
      
  # Job para o Django com Docker e DNS SD
  - job_name: 'django'
    metrics_path: /metrics
    scrape_interval: 30s  # Intervalo de coleta das métricas
    dns_sd_configs:
      - names: ["ecommerce"]
        type: A
        port: 8000 # Usando o IP diretamente para o Django
 # Seu serviço Django

  # Job para o Redis (redis_exporter)
  - job_name: 'redis'
    metrics_path: /metrics
    static_configs:
      - targets: ['redis_exporter:9121']  # Seu serviço Redis Exporter

  # Exemplo de configuração estática para Rocket.Chat
  - job_name: rocketchat_static
    static_configs:
      - targets:
          - rocketchat1:9458
          - rocketchat2:9458

  # Exemplo de configuração com Docker e DNS SD
  - job_name: rocketchat_docker
    scrape_interval: 30s
    dns_sd_configs:
      - names: ["rocketchat"]
        type: A
        port: 9458
