scrape_configs:
  # if you just have single or multiple, but static instances - you
  # can use the static configuration below.
  - job_name: rocketchat_static
    static_configs:
      - targets:
          - rocketchat1:9458
          - rocketchat2:9458

  # If you use a Docker-based setup make sure to use the DNS
  # discovery to always include all available application instances
  # of Rocket.Chat
  - job_name: rocketchat_docker
    scrape_interval: 30s
    dns_sd_configs:
      - names: ["alcateia-rocketchat-1"]
        type: A
        port: 9458

  # Job para métricas customizadas do projeto
  - job_name: 'noxid_metrics'
    metrics_path: /metrics_noxid
    static_configs:
      - targets: ['ecommerce:8000']

  # Job para o Django
  - job_name: 'django'
    metrics_path: /metrics
    static_configs:
      - targets: ['ecommerce:8000']

  # Job para o Redis (redis_exporter)
  - job_name: 'redis'
    metrics_path: /metrics
    static_configs:
      - targets: ['redis_exporter:9121']
